services:
  - type: web
    name: laravel-form-builder
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:80pAbP4FNsYLbH0d1vR8TNTxJ7AXvZnr7gCxQFplNFo=
      - key: APP_URL
        value: https://form-builder-sswk.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1qcgk3uibrs73eit6bg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: formbuilder_db_ikxk
      - key: DB_USERNAME
        value: zmm96sdVTf5cV6ctapR7jt66NvdyewEM
      - key: DB_PASSWORD
        value: zmm96sdVTf5cV6ctapR7jt66NvdyewEM
