[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.fileinfo",
  "php82Extensions.mbstring",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.curl",
  "php82Extensions.bcmath",
  "php82Extensions.zip"
]

[phases.build]
cmds = ["./build.sh"]

[start]
cmd = "php -S 0.0.0.0:8080 -t public"
